### ISSUE TITLE
Editing number of pixels on Virtual RGB Matrix Display

### ISSUE THREAD

**Issue by ZommyT** [tajhlande/lmae#9]
Hello,

I found the link to this project on the discord forum for hzellers rpi-rgb-led-matrix project (https://rpi-rgb-led-matrix.discourse.group/t/running-simultaneous-scrolling-text-at-different-y-positions/726)  and was intreged cause it looks like what I was looking for so I decided to download and play around.

I was wondering how I would go about making the virtual rgb matrix display be representative of a different set size matrix set up. I currently have 4 matrix of size 64x32, arranged so that it is 128 x 64 and wanted to make the virtual board representative of that. 

I tried editing the matrix options in the class VirtualRGBMatrixOptions in the file display.py but that did not work when I tried to run the sprite_module_test.py (still showed up as a 64 x 32 pixel virtual display). 

Please let me know. How I can do this.

Thanks for the project and I look forward to your answer (I am sure I will have more questions in the future too)

**Comment by tajhlande** [comment]
First, I am sorry to say... the demo is currently broken!  I didn't realize this until just now. I have been lax about testing in a project that has thus far only of interest to myself, but I'll fix that as soon as I can.  

The command line options for matrix size are inherited from the [hzeller/rpi-rgb-led-matrix](https://github.com/hzeller/rpi-rgb-led-matrix) project examples: `--led-rows=XX` and `--led-cols=YY` are the command line options to set more rows and columns. I probably should work on the render test example to be more tolerant of different matrix sizes. In theory, the code in this library should work for non-default values there, but I don't have more matrices to test it.

**Comment by tajhlande** [comment]
I pushed some bug fixes and tested the `render_test.py` demo for myself using the command line parameters to set non-default rows and columns.  @ZommyT Give it a try!

**Comment by ZommyT** [comment]
Thanks so much for taking the time to work on this. I really appreciate it. 

To be honest with you, I never even tried changing the columns and rows via command line flags. I just tried it on render_test.py and it worked great. I am now able to change to non-default board sizes (might have always been able to and no update was needed, was probably just user error on my end from the start, lol sorry).

I do still have one small bug that is worth mentioning.

When running hzeller's full library on RPi, the board automatically will adjust based on the flags --led-chain and --led-parallel. However, when running the virtual matrix board on your program, you have to adjust using --led-rows and --led-cols with the specific size you want. Doing --led-chain=2 --led-parallel=2 actually still produces the default board of 64x32, rather than a 128x64 (which is the 64x32 two across chained and two down parallel). It would be nice if the rows and columns automatically adjusted and displayed correctly with just the two flags chain and parallel.

Again, this is low priority and not a big deal but just thought I'd mention it.

As a heads up, I will also be creating a few more Issue threads today with some improvements/issues/difficulties I am having. Don't take them as criticism as I am loving the project and grateful for your work and sharing. Thanks and blessings.

**Comment by ZommyT** [comment]
Thanks so much for taking the time to work on this. I really appreciate it. 

To be honest with you, I never even tried changing the columns and rows via command line flags. I just tried it on render_test.py and it worked great. I am now able to change to non-default board sizes (might have always been able to and no update was needed, was probably just user error on my end from the start, lol sorry).

I do still have one small bug that is worth mentioning.

When running hzeller's full library on RPi, the board automatically will adjust based on the flags --led-chain and --led-parallel. However, when running the virtual matrix board on your program, you have to adjust using --led-rows and --led-cols with the specific size you want. Doing --led-chain=2 --led-parallel=2 actually still produces the default board of 64x32, rather than a 128x64 (which is the 64x32 two across chained and two down parallel). It would be nice if the rows and columns automatically adjusted and displayed correctly with just the two flags chain and parallel.

Again, this is low priority and not a big deal but just thought I'd mention it.

As a heads up, I will also be creating a few more Issue threads today with some improvements/issues/difficulties I am having. Don't take them as criticism as I am loving the project and grateful for your work and sharing. Thanks and blessings.

**Comment by tajhlande** [comment]
I'll call this one resolved with the merged fixes
